### ISSUE TITLE
Sprint 1 - Demo

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/cs3892015team5#19]
You did what you said you will do! So very good!

Credit should be given to images that require it.

Try to have a consistent look for your app

The video (<2 minutes) should be on the wiki.

@williamokano @JsLucasSf

**Comment by williamokano** [comment]
The demo was posted on the same day past 3 p.m.

**Comment by scharffc** [comment]
I did not see it when I checked.

**Comment by jslucassf** [comment]
The issue was opened at 10:31 AM, we posted the Demo at 3 PM.

**Comment by scharffc** [comment]
The deadline was Thursday not the day I graded which is Sunday.
