### ISSUE TITLE
Software Process Reflection

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/cs3892015team5#21]
The software process is not present. You may have done it but it is not on the wiki and I thus consider it was not done.

@williamokano @JsLucasSf 

![image](https://cloud.githubusercontent.com/assets/761057/7050530/fbe7c3b8-ddef-11e4-824d-4e6884be7c40.png)

**Comment by evapzy** [comment]
I have written the softwareprocessreflection. But I put it in the content, I will put it in the software process.
